### PR TITLE
#07 dev-issue07

### PR DESCRIPTION
**Pull request by nikolay-mamaev**
Implemented MVP "Send text & image" flow. In the absence of database, phone numbers are hardcoded, see MatchViewController.swift, `debugInitData()` function.

### CODE REVIEW

**Comment by stevenZlai** [comment]
@nikolay-mamaev I currently have this branch checked out. How should I QA this phone number function (or is it best to wait until we make backend API calls)?

**Comment by nikolay-mamaev** [comment]
Please change phone numbers (4089178180 and 4089159815) in the file named MatchViewController.swift, debugInitData() function. Please let me know if there are any issues with changing and verifying.

**Comment by nikolay-mamaev** [comment]
Well, my previous comment is valid if you can build and run the app on your iPhone. Can you?

**Comment by stevenZlai** [comment]
Ok yeah got it

**Comment by stevenZlai** [comment]
@BKPetkov This looks good from my QA. Can you please inspect the integrity of the code? 
@nikolay-mamaev Let's merge into the dev branch, not the master branch- merges into master will come following a QA with Lisa

**Comment by stevenZlai** [comment]
Actually, @nikolay-mamaev i gave it double check- it looks like the date string isn't included yet. Can we add that in before merge?

**Comment by BKPetkov** [comment]
Code looks good to me. (Not sure about the date string mentioned above)

**Comment by nikolay-mamaev** [comment]
@stevenZlai I thought the date should be a part of issue #9?

**Pull request merged**
